"""
Application constants for timeline service.
"""

# Valid incident statuses
INCIDENT_STATUS_OPEN = "OPEN"
INCIDENT_STATUS_INVESTIGATING = "INVESTIGATING"
INCIDENT_STATUS_RESOLVED = "RESOLVED"
INCIDENT_STATUS_CLOSED = "CLOSED"

VALID_INCIDENT_STATUSES = {
    INCIDENT_STATUS_OPEN,
    INCIDENT_STATUS_INVESTIGATING,
    INCIDENT_STATUS_RESOLVED,
    INCIDENT_STATUS_CLOSED,
}

# Valid incident severities
INCIDENT_SEVERITY_LOW = "LOW"
INCIDENT_SEVERITY_MEDIUM = "MEDIUM"
INCIDENT_SEVERITY_HIGH = "HIGH"
INCIDENT_SEVERITY_CRITICAL = "CRITICAL"

VALID_INCIDENT_SEVERITIES = {
    INCIDENT_SEVERITY_LOW,
    INCIDENT_SEVERITY_MEDIUM,
    INCIDENT_SEVERITY_HIGH,
    INCIDENT_SEVERITY_CRITICAL,
}

# Event types
EVENT_TYPE_INCIDENT_CREATED = "IncidentCreated"
EVENT_TYPE_INCIDENT_STATUS_CHANGED = "IncidentStatusChanged"
EVENT_TYPE_INCIDENT_SEVERITY_CHANGED = "IncidentSeverityChanged"
EVENT_TYPE_INCIDENT_RESOLVED = "IncidentResolved"
EVENT_TYPE_TIMELINE_COMMENT_ADDED = "TimelineCommentAdded"

CONSUMABLE_EVENT_TYPES = {
    EVENT_TYPE_INCIDENT_CREATED,
    EVENT_TYPE_INCIDENT_STATUS_CHANGED,
    EVENT_TYPE_INCIDENT_SEVERITY_CHANGED,
    EVENT_TYPE_INCIDENT_RESOLVED,
}

# Event envelope version
EVENT_ENVELOPE_VERSION = "1.0"

# DynamoDB attributes
ATTR_INCIDENT_ID = "incident_id"
ATTR_TIMELINE_ENTRY_ID = "timeline_entry_id"
ATTR_CREATED_AT = "created_at"
ATTR_SOURCE_EVENT_ID = "source_event_id"
ATTR_MESSAGE = "message"
ATTR_EVENT_TYPE = "event_type"

# SQS configuration
SQS_MAX_MESSAGES = 10
SQS_WAIT_TIME = 20  # Long polling duration
SQS_VISIBILITY_TIMEOUT = 300  # 5 minutes
