"""
Application constants for audit worker service.
"""

# Valid incident statuses
INCIDENT_STATUS_OPEN = "OPEN"
INCIDENT_STATUS_INVESTIGATING = "INVESTIGATING"
INCIDENT_STATUS_RESOLVED = "RESOLVED"
INCIDENT_STATUS_CLOSED = "CLOSED"

VALID_INCIDENT_STATUSES = {
    INCIDENT_STATUS_OPEN,
    INCIDENT_STATUS_INVESTIGATING,
    INCIDENT_STATUS_RESOLVED,
    INCIDENT_STATUS_CLOSED,
}

# Valid incident severities
INCIDENT_SEVERITY_LOW = "LOW"
INCIDENT_SEVERITY_MEDIUM = "MEDIUM"
INCIDENT_SEVERITY_HIGH = "HIGH"
INCIDENT_SEVERITY_CRITICAL = "CRITICAL"

VALID_INCIDENT_SEVERITIES = {
    INCIDENT_SEVERITY_LOW,
    INCIDENT_SEVERITY_MEDIUM,
    INCIDENT_SEVERITY_HIGH,
    INCIDENT_SEVERITY_CRITICAL,
}

# Event types
EVENT_TYPE_INCIDENT_CREATED = "IncidentCreated"
EVENT_TYPE_INCIDENT_STATUS_CHANGED = "IncidentStatusChanged"
EVENT_TYPE_INCIDENT_SEVERITY_CHANGED = "IncidentSeverityChanged"
EVENT_TYPE_INCIDENT_RESOLVED = "IncidentResolved"
EVENT_TYPE_TIMELINE_COMMENT_ADDED = "TimelineCommentAdded"

# Consumable event types (audit-worker processes these)
CONSUMABLE_EVENT_TYPES = {
    EVENT_TYPE_INCIDENT_CREATED,
    EVENT_TYPE_INCIDENT_STATUS_CHANGED,
    EVENT_TYPE_INCIDENT_SEVERITY_CHANGED,
    EVENT_TYPE_INCIDENT_RESOLVED,
}

# Event envelope version
EVENT_ENVELOPE_VERSION = "1.0"

# DynamoDB attributes
ATTR_AUDIT_ID = "audit_id"
ATTR_RESOURCE_ID = "resource_id"
ATTR_RESOURCE_TYPE = "resource_type"
ATTR_CREATED_AT = "created_at"
ATTR_SOURCE_EVENT_ID = "source_event_id"
ATTR_EVENT_TYPE = "event_type"
ATTR_ACTION = "action"
ATTR_ACTOR_ID = "actor_id"
ATTR_ACTOR_NAME = "actor_name"
ATTR_DETAILS = "details"

# Resource types
RESOURCE_TYPE_INCIDENT = "incident"

# Audit actions
AUDIT_ACTION_CREATED = "CREATED"
AUDIT_ACTION_STATUS_CHANGED = "STATUS_CHANGED"
AUDIT_ACTION_SEVERITY_CHANGED = "SEVERITY_CHANGED"
AUDIT_ACTION_RESOLVED = "RESOLVED"

# SQS configuration
SQS_MAX_MESSAGES = 10
SQS_WAIT_TIME = 20  # Long polling duration
SQS_VISIBILITY_TIMEOUT = 300  # 5 minutes
